### ISSUE TITLE
Similar SparseMatrixCOO

### ISSUE THREAD

**Issue by MaxenceGollier** [JuliaSmoothOptimizers/SparseMatricesCOO.jl#39]
There is a problem when trying to allocate memory for a similar SparseMatrixCOO type.
For any matrix,
```
A = SparseMatrixCOO(matrix)
B = similar(A)
```
and `typeof(B)` returns `Matrix` type. I guess this is due to the fact that `SparseMatrixCOO <: Matrix` and that `similar( A :: SparseMatrixCOO)` is not implemented ? I can add a PR with this method if this makes sense.

**Comment by dpo** [comment]
A PR would make sense.

**Comment by dpo** [comment]
Implemented in #40.

**Comment by MaxenceGollier** [comment]
With #40, when calling 
```
B = similar(A)
```
on a matrix `A` of type `SparseMatrixCOO`, we don't copy the sparsity pattern of `A` into `B` (this obviously leads to errors and is what SparseArrays.jl does for example).
I solved this issue in a new PR #46.
