### ISSUE TITLE
Why is the SparseMatrixCOO mutable?

### ISSUE THREAD

**Issue by albertomercurio** [JuliaSmoothOptimizers/SparseMatricesCOO.jl#44]
Hello,

looking at the code I noticed that the `SparseMatrixCOO` constructor is mutable, while the `SparseMatrixCSC` one is not.

I think that it can be safely converted into immutable. Am I wrong?

**Comment by dpo** [comment]
It’s useful to keep it mutable because in optimizations, a Hessian or Jacobian often retains the same sparsity pattern; only the nonzero values change from one iteration to the next. That is what happens in NLPModels.jl.

**Comment by albertomercurio** [comment]
But than one can still change the `vals` vector inplace. The struct would be immutable, but the vectors inside not. Even for the `SparseMatrixCSC` I can update its nonzero values.

**Comment by dpo** [comment]
Well, yes, I suppose you're right. Do you need the struct to be immutable for a special reason? Or just for uniformity with SparseMatrixCSC?

**Comment by albertomercurio** [comment]
Yes, for sure because of uniformity. But also because immutable structs would be also faster AFAIK.

**Comment by dpo** [comment]
Sounds good. Would you like to submit a PR?

**Comment by albertomercurio** [comment]
Yes, why not. When I will have some free time I will do it.

**Comment by dpo** [comment]
Done in #54.
